### ISSUE TITLE
Dynamic obstacle avoidance not working properly

### ISSUE THREAD

**Issue by emilcw** [Zhefan-Xu/DEP#1]
Hi @Zhefan-Xu!

Thank you for your excellent work!

I have tried out your project and cannot make the planner replan when there is dynamic obstacle in the way. If a dynamic obstacle comes in the way between two nodes, the drone simply drives straight through it. Is there any sort of setting or parameter that you have to adjust to make this work? Also, could you provide a video/gif/image where it handles dynamic obstacles and where you can the see replanning step in action.

Thanks

**Comment by Zhefan-Xu** [comment]
Hi @emilcw, apologize for this super late reply but I must have missed it. The thing is that it handles dynamic obstacles by having a less replan time comapred to other algorithms, but still have chance to collide with dynamic obstacle due to the their unpredictable natrue. However, I have integrated this work to our latest repo and it can perform more robust to dynamic obstacles: https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy.
